name: Export ONNX Runtime wheel

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/export-onnxruntime.yml"

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Download wheels
        run: python -m pip download --only-binary=:all: --dest wheels onnxruntime==1.23.2
      - uses: actions/upload-artifact@v4
        with:
          name: onnxruntime-py313-linux
          path: wheels
          retention-days: 1
          compression-level: 0
